(executable
 (name fuzz_parser)
 (modules fuzz_parser)
 (libraries alcobar))

(executable
 (alias runtest)
 (deps fuzz_parser.exe)
 (action
  (run %{exe:fuzz_parser.exe})))

(rule
 (alias fuzz)
 (enabled_if
  (= %{profile} afl))
 (deps
  (source_tree corpus)
  fuzz_parser.exe
 (action
  (progn
   (run afl-fuzz -V 60 -i corpus -o _fuzz -- %{exe:fuzz_parser.exe} @@))))
