(** Render rule documentation in the format the user asks for. *)

type format = Text | Markdown | Html

let category_of_code code =
  let n = int_of_string (String.sub code 1 (String.length code - 1)) in
  if n < 100 then "Complexity"
  else if n < 200 then "Security/Safety"
  else if n < 300 then "Style/Modernization"
  else if n < 400 then "Naming Conventions"
  else if n < 500 then "Documentation"
  else if n < 600 then "Project Structure"
  else "Testing"

let categories =
  [
    ("Complexity", "E001-E099", "Code complexity and maintainability issues");
    ( "Security/Safety",
      "E100-E199",
      "Potential security vulnerabilities and unsafe code patterns" );
    ( "Style/Modernization",
      "E200-E299",
      "Code style and modernization recommendations" );
    ( "Naming Conventions",
      "E300-E399",
      "Identifier naming convention violations" );
    ("Documentation", "E400-E499", "Missing or incorrect documentation");
    ( "Project Structure",
      "E500-E599",
      "Project organization and configuration issues" );
    ("Testing", "E600-E699", "Test coverage and test quality issues");
  ]

(* {1 Text — plain terminal output} *)

module Text = struct
  let example (ex : Rule.example) =
    let label = if ex.is_good then "Good:" else "Bad:" in
    Fmt.str "  %s\n%s\n" label
      (String.split_on_char '\n' ex.code
      |> List.map (fun l -> "    " ^ l)
      |> String.concat "\n")

  let render_rule rule =
    let buf = Buffer.create 256 in
    let ppf = Fmt.with_buffer buf in
    Fmt.pf ppf "[%s] %s\n" (Rule.code rule) (Rule.title rule);
    Fmt.pf ppf "  Category: %s\n" (category_of_code (Rule.code rule));
    Fmt.pf ppf "\n%s\n" (Rule.hint rule);
    (match Rule.examples rule with
    | [] -> ()
    | exs ->
        Buffer.add_string buf "\nExamples:\n";
        List.iter (fun ex -> Buffer.add_string buf (example ex)) exs);
    Buffer.contents buf

  let render_all rules =
    rules |> List.map render_rule
    |> String.concat "\n----------------------------------------\n\n"

  (** One-line-per-rule index: [Ecode  title  (category)]. Grep-friendly: pipe
      through [grep magic] or [grep Naming] to find what you're after. *)
  let render_index rules =
    let max_code =
      List.fold_left
        (fun acc r -> max acc (String.length (Rule.code r)))
        0 rules
    in
    let max_title =
      List.fold_left
        (fun acc r -> max acc (String.length (Rule.title r)))
        0 rules
    in
    rules
    |> List.map (fun r ->
        Fmt.str "%-*s  %-*s  (%s)" max_code (Rule.code r) max_title
          (Rule.title r)
          (category_of_code (Rule.code r)))
    |> String.concat "\n"
end

(* {1 Markdown — style guide} *)

module Markdown = struct
  let example (ex : Rule.example) =
    let label = if ex.is_good then "**Good:**" else "**Bad:**" in
    Fmt.str "%s\n```ocaml\n%s\n```\n" label ex.code

  let examples = function
    | [] -> ""
    | exs ->
        "\n\n**Examples:**\n\n" ^ (List.map example exs |> String.concat "\n")

  let render_rule rule =
    Fmt.str "### [%s] %s\n\n%s%s\n" (Rule.code rule) (Rule.title rule)
      (Rule.hint rule)
      (examples (Rule.examples rule))

  let render_rule_by_code rule_code =
    match List.find_opt (fun r -> Rule.code r = rule_code) Data.all_rules with
    | None -> Fmt.str "### [%s] Rule not found\n\n" rule_code
    | Some r -> render_rule r

  let rec of_guide_element = function
    | Guide.Title s -> Fmt.str "# %s\n" s
    | Section (title, elements) ->
        let content =
          List.map of_guide_element elements |> String.concat "\n"
        in
        Fmt.str "## %s\n\n%s" title content
    | Paragraph s -> Fmt.str "%s\n" s
    | Code s -> Fmt.str "```ocaml\n%s\n```\n" s
    | Rule rule_code -> render_rule_by_code rule_code

  let style_guide () =
    let header =
      "<!-- This file is auto-generated by `merlint help --format=md --all`. -->\n\
       <!-- Do not edit manually. Edit lib/guide.ml instead. -->\n\n"
    in
    let content =
      List.map of_guide_element Guide.content |> String.concat "\n"
    in
    header ^ content

  let render_all _rules = style_guide ()
end

(* {1 HTML — reference documentation} *)

module Html = struct
  let body_styles =
    {|body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    line-height: 1.6;
    color: #333;
    max-width: 1400px;
    margin: 0 auto;
    padding: 20px;
    background: #f8f9fa;
}|}

  let heading_styles =
    {|h1 {
    color: #2c3e50;
    border-bottom: 3px solid #3498db;
    padding-bottom: 10px;
    margin-bottom: 30px;
}
h2 {
    color: #34495e;
    margin-top: 40px;
    margin-bottom: 20px;
    border-bottom: 1px solid #bdc3c7;
    padding-bottom: 8px;
}|}

  let text_styles =
    {|p {
    margin: 1em 0;
    line-height: 1.7;
}
code {
    background-color: #f4f4f4;
    padding: 2px 4px;
    border-radius: 3px;
    font-family: 'SF Mono', Monaco, 'Cascadia Code', 'Roboto Mono', Consolas, 'Courier New', monospace;
    font-size: 0.9em;
    color: #e83e8c;
}
pre {
    background-color: #f8f8f8;
    color: #333;
    padding: 12px 16px;
    border-radius: 6px;
    overflow-x: auto;
    margin: 0.5em 0;
    border: 1px solid #e1e4e8;
}
pre code {
    background-color: transparent;
    color: inherit;
    padding: 0;
    font-size: 0.875em;
    line-height: 1.5;
    font-family: 'SF Mono', Monaco, 'Cascadia Code', 'Roboto Mono', Consolas, 'Courier New', monospace;
    white-space: pre;
}|}

  let card_styles =
    {|.error-card {
    background: white;
    border: 1px solid #e5e7eb;
    border-radius: 8px;
    padding: 18px 20px;
    margin: 16px 0;
    box-shadow: 0 1px 3px rgba(0,0,0,0.1);
    max-width: 1400px;
}
.error-code {
    font-family: 'SF Mono', Monaco, 'Cascadia Code', 'Roboto Mono', Consolas, 'Courier New', monospace;
    font-size: 1.1em;
    font-weight: bold;
    color: #dc2626;
    display: inline-block;
    background: #fee;
    padding: 3px 8px;
    border-radius: 4px;
    margin-right: 10px;
}
.error-title {
    font-size: 1.05em;
    font-weight: 600;
    color: #1f2937;
    display: inline-block;
}
.error-hint {
    margin-top: 12px;
    padding: 0;
}
.error-hint > p {
    padding: 12px 16px;
    background: #eff6ff;
    border-left: 4px solid #3b82f6;
    border-radius: 0 4px 4px 0;
    margin: 0 0 12px 0;
    line-height: 1.6;
    color: #1e40af;
}|}

  let example_grid_styles =
    {|.examples-grid {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 20px;
    margin: 20px 0;
}
@media (max-width: 968px) {
    .examples-grid {
        grid-template-columns: 1fr;
    }
}|}

  let example_box_styles =
    {|.example {
    border-radius: 6px;
    overflow: hidden;
    box-shadow: 0 1px 3px rgba(0,0,0,0.1);
}
.example.bad {
    border: 1px solid #fecaca;
    background-color: #fef2f2;
}
.example.good {
    border: 1px solid #bbf7d0;
    background-color: #f0fdf4;
}
.example h4 {
    margin: 0;
    padding: 8px 12px;
    font-size: 0.8em;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.5px;
}
.example.bad h4 {
    background-color: #fecaca;
    color: #991b1b;
}
.example.good h4 {
    background-color: #bbf7d0;
    color: #14532d;
}|}

  let example_content_styles =
    {|.example pre {
    margin: 0;
    padding: 12px 16px;
    border-radius: 0;
    border-top: 1px solid rgba(0,0,0,0.1);
    background-color: #f8f8f8;
    font-size: 0.85em;
    overflow-x: auto;
}
.example.bad pre {
    background-color: #fffafa;
}
.example.good pre {
    background-color: #f8fffe;
}
.example pre code {
    background-color: transparent;
    color: #333;
    padding: 0;
}
.category {
    color: #7f8c8d;
    font-size: 0.9em;
    margin-bottom: 20px;
}|}

  let nav_styles =
    {|.toc {
    background: white;
    border: 1px solid #ddd;
    border-radius: 8px;
    padding: 20px;
    margin-bottom: 30px;
}
.toc h2 {
    margin-top: 0;
    margin-bottom: 15px;
    border: none;
    padding-bottom: 0;
}
.toc ul {
    list-style-type: none;
    padding-left: 0;
    margin: 0;
}
.toc li {
    margin: 8px 0;
}
.toc a {
    color: #3498db;
    text-decoration: none;
    display: block;
    padding: 4px 0;
    transition: color 0.2s ease;
}
.toc a:hover {
    color: #2980b9;
    text-decoration: underline;
}
.back-to-top {
    position: fixed;
    bottom: 20px;
    right: 20px;
    background: #3498db;
    color: white;
    padding: 10px 15px;
    border-radius: 5px;
    text-decoration: none;
    opacity: 0.8;
    transition: opacity 0.2s ease;
    box-shadow: 0 2px 4px rgba(0,0,0,0.2);
}
.back-to-top:hover {
    opacity: 1;
}|}

  let syntax_highlighting_styles =
    {|/* Syntax highlighting */
.kw { color: #0000ff; font-weight: 600; }
.st { color: #a31515; }
.cm { color: #008200; font-style: italic; }
.nu { color: #098658; }
.cn { color: #267f99; }
.md { color: #267f99; font-weight: 600; }
.fn { color: #795E26; }

@media (max-width: 768px) {
    body { padding: 10px; }
    .error-card { padding: 15px; }
    pre { padding: 10px; font-size: 0.8em; }
}|}

  let style =
    String.concat "\n"
      [
        body_styles;
        heading_styles;
        text_styles;
        card_styles;
        example_grid_styles;
        example_box_styles;
        example_content_styles;
        nav_styles;
        syntax_highlighting_styles;
      ]

  let escape s =
    s |> String.split_on_char '&' |> String.concat "&amp;"
    |> String.split_on_char '<' |> String.concat "&lt;"
    |> String.split_on_char '>' |> String.concat "&gt;"
    |> String.split_on_char '"' |> String.concat "&quot;"

  let ocaml_keywords =
    [
      "let";
      "in";
      "if";
      "then";
      "else";
      "match";
      "with";
      "fun";
      "function";
      "try";
      "type";
      "module";
      "open";
      "and";
      "or";
      "not";
      "rec";
      "when";
      "as";
      "of";
      "begin";
      "end";
      "struct";
      "sig";
      "val";
      "include";
      "for";
      "while";
      "do";
      "done";
      "to";
      "ref";
      "mutable";
      "new";
      "class";
      "object";
      "method";
      "inherit";
      "external";
      "exception";
      "raise";
      "assert";
      "lazy";
      "true";
      "false";
    ]

  let add_pattern pattern class_name escaped segments =
    let re = Re.Perl.compile_pat pattern in
    Re.all re escaped
    |> List.iter (fun g ->
        let start = Re.Group.start g 0 in
        let stop = Re.Group.stop g 0 in
        let text = Re.Group.get g 0 in
        segments := (start, stop, class_name, text) :: !segments)

  let add_keywords escaped segments =
    List.iter
      (fun kw ->
        let pattern = Fmt.kstr Re.Perl.compile_pat {|\b%s\b|} kw in
        Re.all pattern escaped
        |> List.iter (fun g ->
            let start = Re.Group.start g 0 in
            let stop = Re.Group.stop g 0 in
            segments := (start, stop, "kw", kw) :: !segments))
      ocaml_keywords

  let drop_overlaps segments =
    let sorted =
      List.sort (fun (s1, _, _, _) (s2, _, _, _) -> compare s1 s2) segments
    in
    let acc = ref [] in
    let last = ref (-1) in
    List.iter
      (fun (start, stop, c, t) ->
        if start >= !last then begin
          acc := (start, stop, c, t) :: !acc;
          last := stop
        end)
      sorted;
    List.rev !acc

  let span c t = Fmt.str {|<span class="%s">%s</span>|} c t

  let module_path text =
    match String.split_on_char '.' text with
    | [ m; f ] ->
        Fmt.str {|<span class="md">%s</span>.<span class="fn">%s</span>|} m f
    | _ -> text

  let render_segment c t = if c = "module_path" then module_path t else span c t

  let weave escaped segments =
    let buf = Buffer.create (String.length escaped + 32) in
    let last = ref 0 in
    List.iter
      (fun (start, stop, c, t) ->
        if start > !last then
          Buffer.add_substring buf escaped !last (start - !last);
        Buffer.add_string buf (render_segment c t);
        last := stop)
      segments;
    if !last < String.length escaped then
      Buffer.add_substring buf escaped !last (String.length escaped - !last);
    Buffer.contents buf

  let highlight code =
    let process line =
      let escaped = escape line in
      let segments = ref [] in
      add_pattern {|\(\*.*?\*\)|} "cm" escaped segments;
      add_pattern {|"(?:[^"\\]|\\.)*"|} "st" escaped segments;
      add_pattern {|\b[0-9]+\.?[0-9]*\b|} "nu" escaped segments;
      add_keywords escaped segments;
      add_pattern {|\b[A-Z][a-zA-Z0-9_']*\.[a-z][a-zA-Z0-9_']*\b|} "module_path"
        escaped segments;
      add_pattern {|\b[A-Z][a-zA-Z0-9_']*\b|} "cn" escaped segments;
      weave escaped (drop_overlaps !segments)
    in
    code |> String.split_on_char '\n' |> List.map process |> String.concat "\n"

  let header =
    Fmt.str
      {|<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Merlint Error Codes Reference</title>
    <style>
%s
    </style>
</head>
<body>
|}
      style

  let footer =
    {|
    <a href="#top" class="back-to-top">↑ Top</a>
</body>
</html>
|}

  let format_hint rule =
    let hint = Rule.hint rule in
    let examples = Rule.examples rule in
    let example_block =
      if examples = [] then ""
      else
        let bad = List.filter (fun ex -> not ex.Rule.is_good) examples in
        let good = List.filter (fun ex -> ex.Rule.is_good) examples in
        let one ex =
          let label = if ex.Rule.is_good then "GOOD" else "BAD" in
          Fmt.str
            {|<div class="example %s">
  <h4>%s</h4>
  <pre><code>%s</code></pre>
</div>|}
            (if ex.Rule.is_good then "good" else "bad")
            label (highlight ex.Rule.code)
        in
        if bad <> [] && good <> [] then
          let bad_html = String.concat "\n" (List.map one bad) in
          let good_html = String.concat "\n" (List.map one good) in
          Fmt.str {|<div class="examples-grid">
%s
%s
</div>|} bad_html
            good_html
        else "\n" ^ String.concat "\n" (List.map one examples)
    in
    Fmt.str "<p>%s</p>%s" (escape hint) example_block

  let render_rule rule =
    Fmt.str
      {|<div class="error-card" id="%s">
    <div>
        <span class="error-code">%s</span>
        <span class="error-title">%s</span>
    </div>
    <div class="error-hint">%s</div>
</div>|}
      (Rule.code rule) (Rule.code rule) (Rule.title rule) (format_hint rule)

  let toc =
    Fmt.str
      {|<div class="toc" id="top">
<h2>Table of Contents</h2>
<ul>
%s
</ul>
</div>|}
      (categories
      |> List.map (fun (name, range, _) ->
          let anchor =
            String.lowercase_ascii name
            |> String.map (fun c -> if c = '/' then '-' else c)
          in
          Fmt.str {|<li><a href="#%s">%s (%s)</a></li>|} anchor name range)
      |> String.concat "\n")

  let render_category rules (name, range, description) =
    let anchor =
      String.lowercase_ascii name
      |> String.map (fun c -> if c = '/' then '-' else c)
    in
    let body =
      rules
      |> List.filter (fun r -> category_of_code (Rule.code r) = name)
      |> List.map render_rule |> String.concat "\n"
    in
    Fmt.str {|<h2 id="%s">%s</h2>
<div class="category">%s • %s</div>
%s|}
      anchor name range description body

  let render_all rules =
    let body =
      categories |> List.map (render_category rules) |> String.concat "\n"
    in
    Fmt.str
      {|%s
<h1>Merlint Error Codes Reference</h1>
<p>This document lists all error codes that Merlint can detect, along with their descriptions and fix hints.</p>
%s
%s
%s|}
      header toc body footer
end

(* {1 Dispatch} *)

let err_unknown_format s =
  Fmt.kstr
    (fun msg -> Error msg)
    "unknown format %S (expected: text, md, html)" s

let format_of_string = function
  | "text" -> Ok Text
  | "md" | "markdown" -> Ok Markdown
  | "html" -> Ok Html
  | s -> err_unknown_format s

let render_rule ~format rule =
  match format with
  | Text -> Text.render_rule rule
  | Markdown -> Markdown.render_rule rule
  | Html -> Html.render_rule rule

let render_all ~format rules =
  match format with
  | Text -> Text.render_all rules
  | Markdown -> Markdown.render_all rules
  | Html -> Html.render_all rules

let render_index = Text.render_index
