(include_subdirs unqualified)

(library
 (public_name merlint)
 (name merlint)
 (libraries
  merlin
  compiler-libs.common
  eio
  re
  logs
  fmt
  astring
  fpath
  merlin-lib.ocaml_parsing
  merlin-lib.ocaml_typing
  console
  nox-opam
  nox-dune
  nox-toml
  bytesrw
  nox-sexp
  probe
  project-index
  unix))

(rule
 (target examples.ml)
 (deps
  ../scripts/generate_examples_ml.exe
  (source_tree ../test/cram))
 (action
  (chdir
   ..
   (with-stdout-to
    lib/examples.ml
    (run scripts/generate_examples_ml.exe)))))

(rule
 (target examples.mli)
 (deps
  ../scripts/generate_examples_ml.exe
  (source_tree ../test/cram))
 (action
  (chdir
   ..
   (with-stdout-to
    lib/examples.mli
    (run scripts/generate_examples_ml.exe mli)))))

(alias
 (name gen)
 (deps examples.ml examples.mli))
