(include_subdirs unqualified)

(library
 (public_name merlint)
 (name merlint)
 (libraries
  ocaml-merlin
  compiler-libs.common
  eio
  re
  logs
  fmt
  astring
  fpath
  vlog
  tty
  jsont
  jsont.bytesrw
  sexpt))

(rule
 (target examples.ml)
 (deps
  ../bin/generate_examples_ml.exe
  (source_tree ../test/cram))
 (action
  (chdir
   ..
   (with-stdout-to
    lib/examples.ml
    (run bin/generate_examples_ml.exe)))))

(alias
 (name gen)
 (deps examples.ml))
