(executable
 (name fuzz_parser)
 (modules fuzz_parser)
 (libraries alcobar))

(rule
 (alias runtest)
 (deps fuzz_parser.exe)
 (action
  (run %{exe:fuzz_parser.exe})))

(rule
 (alias fuzz)
 (deps
  (source_tree input)
  fuzz_parser.exe)
 (action
  (echo "AFL fuzzer built: %{exe:fuzz_parser.exe}\n")))
