(executable
 (name generate_examples_ml)
 (modules generate_examples_ml)
 (libraries unix fmt))

(executable
 (name check_test_integrity)
 (modules check_test_integrity)
 (libraries merlint unix re fmt))

(executable
 (name trace)
 (modules trace)
 (libraries runtime_events fmt))

(mdx
 (libraries merlint)
 (files README.md))
